### ISSUE TITLE
typos in your text

### ISSUE THREAD

**Issue by pleabargain** [florinpop17/quiz-app#1]
I did try to find the source file but no joy :(

here's the screengrab
http://www.openscreenshot.com/HkVDNm29l

**Comment by florinpop17** [comment]
@pleabargain Could you tell me what do you mean by trying to find the source file?
I also fixed the typos. Thank you.

**Comment by florinpop17** [comment]
You were right. It seems that it wasn't connected to my heroku and didn't auto-deploy. Fixing now...
Also the source file is [here](https://github.com/florinpop17/quiz-app/blob/master/app/data/data.js)

**Comment by pleabargain** [comment]
Coolio! Good work!
